/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;

/**
 *
 * @author HP
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }
    
    public JLabel getRock() {
        return lbRock;
    }

    public JLabel getPaper() {
        return lbPaper;
    }

    public JLabel getScissor() {
        return lbScissor;
    }

    public JLabel getCounter() {
        return lbCounter;
    }

    public JLabel getYourChoice() {
        return lbYourChoice;
    }

    public JLabel getOpponentChoice() {
        return lbOpponentChoice;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRock = new javax.swing.JLabel();
        lbPaper = new javax.swing.JLabel();
        lbScissor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbCounter = new javax.swing.JLabel();
        lbOpponentChoice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbYourChoice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbRock.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rock-2.png"))); // NOI18N
        lbRock.setText("Rock");
        lbRock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbPaper.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paper-2.png"))); // NOI18N
        lbPaper.setText("Paper");
        lbPaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbPaper.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbScissor.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbScissor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/scissor-2.png"))); // NOI18N
        lbScissor.setText("Scissor");
        lbScissor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbScissor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("You");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Opponent Player");

        lbCounter.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lbCounter.setForeground(new java.awt.Color(51, 51, 255));
        lbCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCounter.setText("15s");

        lbOpponentChoice.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbOpponentChoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOpponentChoice.setText("Opponent choosing...");

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("*Please choose at least one option before time runs out");

        lbYourChoice.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbYourChoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbYourChoice.setText("Your choice: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbYourChoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbOpponentChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbRock)
                        .addGap(76, 76, 76)
                        .addComponent(lbPaper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(lbScissor)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addComponent(lbOpponentChoice)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lbCounter)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPaper)
                    .addComponent(lbRock)
                    .addComponent(lbScissor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lbYourChoice)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbCounter;
    private javax.swing.JLabel lbOpponentChoice;
    private javax.swing.JLabel lbPaper;
    private javax.swing.JLabel lbRock;
    private javax.swing.JLabel lbScissor;
    private javax.swing.JLabel lbYourChoice;
    // End of variables declaration//GEN-END:variables
}
