/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;

/**
 *
 * @author HP
 */
public class RoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomPanel
     */
    public RoomPanel() {
        initComponents();
    }
    
    public JLabel getRoomId() {
        return lbRommId;
    }
    
    public JLabel getPlayer1() {
        return lbPlayerName1;
    }
    
    public JLabel getPlayer2() {
        return lbPlayerName2;
    }  
    
    public JLabel getTotalMatch1() {
        return lbTotalMatch1;
    }  
    
    public JLabel getTotalMatch2() {
        return lbTotalMatch2;
    }        

    public JLabel getTotalWin1() {
        return lbTotalWin1;
    } 
    
    public JLabel getTotalWin2() {
        return lbTotalWin2;
    }      
    
    public JLabel getScore1() {
        return lbScore1;
    }
    
    public JLabel getScore2() {
        return lbScore2;
    }  
    
    public JButton btnStart() {
        return btnStart;
    }
    
    public JButton btnInvite() {
        return btnInvite;
    }    
    
    public JButton btnLeave() {
        return btnLeave;
    }

    public JList<String> getOnlineListWR() {
        return onlineListWR;
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRommId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlineListWR = new javax.swing.JList<>();
        lbAvatar5 = new javax.swing.JLabel();
        lbVersus2 = new javax.swing.JLabel();
        lbAvatar6 = new javax.swing.JLabel();
        lbPlayerName1 = new javax.swing.JLabel();
        lbPlayerName2 = new javax.swing.JLabel();
        btnLeave = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        lbTotalMatch1 = new javax.swing.JLabel();
        lbTotalWin1 = new javax.swing.JLabel();
        lbScore1 = new javax.swing.JLabel();
        lbTotalMatch2 = new javax.swing.JLabel();
        lbTotalWin2 = new javax.swing.JLabel();
        lbScore2 = new javax.swing.JLabel();
        btnInvite = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbRommId.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbRommId.setForeground(new java.awt.Color(255, 0, 51));
        lbRommId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRommId.setText("Room Id: username");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Online");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        onlineListWR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        onlineListWR.setToolTipText("double-click to send a message");
        jScrollPane3.setViewportView(onlineListWR);

        lbAvatar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_rick_sanchez_96px.png"))); // NOI18N
        lbAvatar5.setBorder(javax.swing.BorderFactory.createTitledBorder("..."));
        lbAvatar5.setOpaque(true);

        lbVersus2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVersus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_sword_48px.png"))); // NOI18N

        lbAvatar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_angry_face_meme_96px.png"))); // NOI18N
        lbAvatar6.setBorder(javax.swing.BorderFactory.createTitledBorder("..."));

        lbPlayerName1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbPlayerName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayerName1.setText("User1");

        lbPlayerName2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbPlayerName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayerName2.setText("User2");

        btnLeave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_exit_sign_24px.png"))); // NOI18N
        btnLeave.setText("Leave");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_ok_24px.png"))); // NOI18N
        btnStart.setText("Start");

        lbTotalMatch1.setText("Total Match: 0");

        lbTotalWin1.setText("Total Win: 0");

        lbScore1.setText("Score: 0");

        lbTotalMatch2.setText("Total Match: 0");

        lbTotalWin2.setText("Total Win: 0");

        lbScore2.setText("Score: 0");

        btnInvite.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInvite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_open_door_24px.png"))); // NOI18N
        btnInvite.setText("Invite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInvite))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTotalWin1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbPlayerName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbAvatar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbScore1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTotalMatch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbVersus2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAvatar6)
                            .addComponent(lbScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTotalMatch2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTotalWin2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeave)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRommId, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRommId)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAvatar5)
                                    .addComponent(lbVersus2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPlayerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAvatar6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbScore2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbTotalMatch2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbScore1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbTotalMatch1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTotalWin1)
                                    .addComponent(lbTotalWin2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnInvite)
                                    .addComponent(btnLeave)
                                    .addComponent(btnStart))
                                .addContainerGap())))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvite;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAvatar5;
    private javax.swing.JLabel lbAvatar6;
    private javax.swing.JLabel lbPlayerName1;
    private javax.swing.JLabel lbPlayerName2;
    private javax.swing.JLabel lbRommId;
    private javax.swing.JLabel lbScore1;
    private javax.swing.JLabel lbScore2;
    private javax.swing.JLabel lbTotalMatch1;
    private javax.swing.JLabel lbTotalMatch2;
    private javax.swing.JLabel lbTotalWin1;
    private javax.swing.JLabel lbTotalWin2;
    private javax.swing.JLabel lbVersus2;
    private javax.swing.JList<String> onlineListWR;
    // End of variables declaration//GEN-END:variables
}
